C:0x
D:0x
T:`prg`fun`arg`sym`res`loc`sym`ast`asn`sym`add`lit`get`ret`get`fun`arg`sym`res`res`ast`ret`add`lit`get`sub`lit`get`fun`arg`sym`res`loc`sym`ast`asn`sym`sym`cal`get`ret`get
P:0 0 1 2 1 1 5 1 7 8 8 10 10 7 13 0 15 16 15 15 15 20 21 22 22 21 25 25 0 28 29 28 28 32 28 34 35 35 35 38 34 40
I:0 0 0 0 0 0 0 0N 1 0 2 1 0N 0N 0N 0 0 0 0 1 0N 0N 2 1 0N 2 1 0N 0 0 0 0 0 0 0N 2 0 0 0N 0N 0N 0N
S:`asn`f`i`x`i`i`r```r`i`i`x`i`r`g`i`x`i`i```i`i`x`i`i`x`h`i`x`i`i`r```x`r`g`x`i`r
