C:0x
D:0x
T:`prg`fun`arg`sym`res`ast`ret`cst`typ`get`fun`arg`sym`res`ast`ret`cst`typ`get`fun`arg`sym`res`ast`ret`cst`typ`get`fun`arg`sym`res`ast`ret`cst`typ`get`fun`arg`sym`res`ast`ret`cst`typ`get`fun`arg`sym`res`ast`ret`cst`typ`get
P:0 0 1 2 1 1 5 6 7 7 0 10 11 10 10 14 15 16 16 0 19 20 19 19 23 24 25 25 0 28 29 28 28 32 33 34 34 0 37 38 37 37 41 42 43 43 0 46 47 46 46 50 51 52 52
I:0 0 0N 0 0N 0N 0N 0N 0N 0N 0 0N 0 0N 0N 0N 0N 0N 0N 0 0N 0 0N 0N 0N 0N 0N 0N 0 0N 0 0N 0N 0N 0N 0N 0N 0 0N 0 0N 0N 0N 0N 0N 0N 0 0N 0 0N 0N 0N 0N 0N 0N
S:`cast`f`i`x`j``j`j`i`x`g`j`x`i``i`i`j`x`h`i`x`f``f`f`i`x`i`f`x`i``i`i`f`x`j`i`x`u``u`u`i`x`k`u`x`i``i`i`u`x
