C:0x
D:0x
T:`prg`fun`arg`sym`res`ast`stm`ret`cst`typ`get`fun`arg`sym`res`ast`stm`ret`cst`typ`get`fun`arg`sym`res`ast`stm`ret`cst`typ`get`fun`arg`sym`res`ast`stm`ret`cst`typ`get`fun`arg`sym`res`ast`stm`ret`cst`typ`get`fun`arg`sym`res`ast`stm`ret`cst`typ`get
P:0 0 1 2 1 1 5 6 7 8 8 0 11 12 11 11 15 16 17 18 18 0 21 22 21 21 25 26 27 28 28 0 31 32 31 31 35 36 37 38 38 0 41 42 41 41 45 46 47 48 48 0 51 52 51 51 55 56 57 58 58
I:0 0 0 0 0 0N 0N 0N 0N 0N 0N 1 0 0 0 0N 0N 0N 0N 0N 0N 2 0 0 0 0N 0N 0N 0N 0N 0N 3 0 0 0 0N 0N 0N 0N 0N 0N 4 0 0 0 0N 0N 0N 0N 0N 0N 5 0 0 0 0N 0N 0N 0N 0N 0N
S:`cast`f`i`x`j````j`i`x`g`j`x`i````i`j`x`h`i`x`f````f`i`x`i`f`x`i````i`f`x`j`i`x`u````u`i`x`k`u`x`i````i`u`x
