C:0x
D:0x
T:`prg`fun`loc`sym`ast`asn`lit`for`nop`nop`stm`asn`add`get`lit`cnd`mor`get`lit`jmp`fun`loc`sym`ast`asn`lit`for`nop`nop`stm`asn`add`get`lit`cnd`mor`get`lit`jmp
P:0 0 1 2 1 4 5 4 7 7 7 10 11 12 12 10 15 16 16 15 0 20 21 20 23 24 23 26 26 26 29 30 31 31 29 34 35 35 34
I:0 0 0N 0 0N 0 0 0 0N 0N 0N 0 2 0N 1 0N 2 0N 3 1 0 0N 0 0N 0 0 0 0N 0N 0N 0 2 0N 1 0N 2 0N 3 1
S:`label`f`i`i``i`i`L````i`i`i`i``i`i`i`L`g`i`i``i`i`````i`i`i`i``i`i`i`
