C:0x
D:0x
T:`prg`fun`loc`sym`ast`for`nop`nop`stm`asn`add`get`lit`cnd`mor`get`lit`jmp`fun`loc`sym`ast`for`nop`nop`stm`asn`add`get`lit`cnd`mor`get`lit`jmp
P:0 0 1 2 1 4 5 5 5 8 9 10 10 8 13 14 14 13 0 18 19 18 21 22 22 22 25 26 27 27 25 30 31 31 30
I:0 0 0N 0 0N 0 0N 0N 0N 0 2 0N 1 0N 2 0N 3 1 0 0N 0 0N 0 0N 0N 0N 0 2 0N 1 0N 2 0N 3 1
S:`label`f`i`i``L````i`i`i`i``i`i`i`L`g`i`i``````i`i`i`i``i`i`i`
