C:0x
D:0x
T:`prg`fun`loc`sym`ast`for`nop`nop`stm`asn`sym`add`get`lit`cnd`mor`get`lit`jmp`fun`loc`sym`ast`for`nop`nop`stm`asn`sym`add`get`lit`cnd`mor`get`lit`jmp
P:0 0 1 2 1 4 5 5 5 8 9 9 11 11 8 14 15 15 14 0 19 20 19 22 23 23 23 26 27 27 29 29 26 32 33 33 32
I:0 0 0 0 0N 0 0N 0N 0N 1 0 2 0N 1 0N 2 0N 3 1 1 0 0 0N 0 0N 0N 0N 1 0 2 0N 1 0N 2 0N 3 1
S:`label`f`i`i``L`````i`i`i`i``i`i`i`L`g`i`i```````i`i`i`i``i`i`i`
