#!/bin/sh
tcc=/local/tcc/tcc
if [ "$1" = "kc" ]; then
	$tcc -o kc.exe -DDRW k_c -luser32 -lgdi32
elif [ "$1" = "u" ]; then
	$tcc -o u.exe u_c -luser32 -lgdi32
elif [ "$1" = "t" ]; then
	sed '/^$/q' t | $tcc -run k_c t | awk '{
		x=$0
		getline < "t"
		y=$0
		if (match(y, /^\//)) next
		gsub(/.* \//, "")
		if(x!=$0) {
			print y"\ngot: "x
			exit
		}
print y,x
	}'
elif [ "$1" = "w" ]; then
	$tcc -run k_c -fw k.wasm -fs ../k.w ../w.k -e 'b:wasm compile s;b~w'
else
	# go test (generate k_c)
	$tcc -run k_c "$*"
fi
