/ ../web/kweb/tok.html

S:" \t"                    /space
L:"({[;\n"                 /left
R:")}]"                    /right
A:"'/\\"                   /adverb
V:"+-*%&|<>=^!~,#_$?@."    /verb


t:"+'a0q`-:e\\/n
;;)+'a0q`-+a'/;
);)+'a0q`++a'';
+;)+'a0q`-+a'';
';)+'a0q`-:a'';
a;)+'bbq`++b'';
0;)+'11q`+:e'';
qrrrrrrtrrrrsrr
`;)+'b0q`++b'';
-;)+'a1q`-+a'';
/ccccccccccccc;
cccccccccccccc;
:;)+'a0q`-+a'';
b;)+'bbq`++b'';
1;)+'11q`++e'';
e;)+'11q`1+1'';
rrrrrrrtrrrrsrr
srrrrrrrrrrrrrr
t;)+'a0q`++a'';"


C:(S,L;R;V;A;".",_,/65 97+\:!26
 "0123456789"),"\"`-:e\\/\n"
C:@[;;]/[-1+&256;0+C;!#C]@0+

q:*'1_"\n"\:t
T:t[;0]?/:1_'t:1_'(&"\n"=t)^t

w:{q@0{T[x;y]}\C x}
s:"-^"@10>q?



in:"phi:(1+%5)%two:200e-2 /golden ratio"

`<(q C in
 w in
 s w in),\:"\n"
