C:0x
D:0x
T:`prg`fun`arg`sym`res`ast`ret`get`fun`arg`sym`res`loc`sym`ast`asn`swc`get`cal`get`stm`asn`cnd`mor`get`lit`sub`get`lit`sub`get`lit`get`ret`get
P:0 0 1 2 1 1 5 6 0 8 9 8 8 12 8 14 15 16 16 18 16 20 21 22 23 23 22 26 26 22 29 29 20 14 33
I:0 0 0N 0 0N 0N 0N 0N 0 0N 0 0N 0N 0 0N 0 1 0N 0N 0N 0N 0 0N 2 0N 5 2 0N 3 2 0N 2 0N 0N 0N
S:`swtch2`f`i`x`i``i`x`g`i`x`i`i`r``r`i`x`f`x``r`i`i`x`i`i`x`i`i`x`i`r`i`r
