#!/bin/sh
tcc=/local/tcc/tcc
if [ "$1" = "fmt" ]; then
	/local/LLVM/bin/clang-format.exe k_c > xx_c
elif [ x"$1" = "xt" ]; then
	while read line; do
		x=`echo $line | awk 'BEGIN{FS=" /"}{print $1}'`
		y=`echo $line | awk 'BEGIN{FS=" /"}{print $2}'`
		z=`$tcc -run k_c $x`
		if [ "$y" != "$z" ]; then
			echo " $line"; echo "$z"
			exit 1
		fi
	done < t
	echo ok
else
	# go test (generate k_c)
	$tcc -run k_c $*
fi
