#!/bin/sh
tcc=/local/tcc/tcc
if [ "$1" = "fmt" ]; then
	/local/LLVM/bin/clang-format.exe k_c > xx_c
elif [ x"$1" = "xt" ]; then
	cat t | $tcc -run k_c t | awk '{
		x=$0
		getline < "t"
		y=$0
		gsub(/.* \//, "")
		if(x!=$0) {
			print y"\ngot: "x
			exit
		}
	}' && echo "ok"
else
	# go test (generate k_c)
	$tcc -run k_c "$*"
fi
