// +build ignore

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
)

var buf *bytes.Buffer

func main() {
	buf = bytes.NewBuffer(nil)

	// cut k-help from ../../readme:^0123457
	b, err := ioutil.ReadFile(`../../readme`)
	if err != nil {
		panic(err)
	}

	idx := panic1(bytes.Index(b, []byte("01234567")))
	b = b[idx:]

	idx = panic1(bytes.Index(b, []byte("------")))
	b = b[:idx]

	help := string(b)

	out("package main\n\n// generated by gen.go\n\n")

	fmt.Fprintf(buf, "var help string = %q\n", help)
	ioutil.WriteFile("s_.go", buf.Bytes(), 0744)
}
func panic1(n int) int {
	if n == -1 {
		panic("gen.go error")
	}
	return n
}

func out(s string) {
	buf.WriteString(s)
}
